/**
 * Provider packs, generated from product/pipeline.json. Original work, MIT.
 *
 * One file decides what the journey is. Four providers read it in four different places
 * under four different filenames, and every one of those files is written from here.
 * The alternative was four hand-maintained copies, which is how the repository ended up
 * with two products in it and no file saying which one a stranger would get.
 *
 * Nothing here writes prose that is not in the pipeline. If a step is missing from a pack
 * it is missing from product/pipeline.json, and that is the only place to add it.
 */

import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
export const PIPELINE_PATH = join(ROOT, 'product/pipeline.json');

export async function loadPipeline(path = PIPELINE_PATH) {
  return JSON.parse(await readFile(path, 'utf8'));
}

/**
 * Where each provider looks, and whether its entry file is the skill's own or written here.
 *
 * `own` means the provider reads SKILL.md, which the skill already carries with the
 * frontmatter that provider needs. Generating a second copy of it would mean two files
 * claiming to be the skill. Those packs are validated against the pipeline instead, which
 * is the same guarantee arrived at from the other side.
 */
export const PROVIDERS = {
  claude: { dir: '.claude/skills/sitesmith', entry: 'SKILL.md', source: 'own',
            what: 'Claude Code reads SKILL.md frontmatter to decide when to load a skill.' },
  codex:  { dir: '.agents/skills/sitesmith', entry: 'AGENTS.md', source: 'generated',
            what: 'Codex reads AGENTS.md.' },
  cursor: { dir: '.cursor/rules/sitesmith', entry: 'sitesmith.mdc', source: 'generated',
            what: 'Cursor reads .mdc rule files with frontmatter globs.' },
  openai: { dir: '.openai/skills/sitesmith', entry: 'SKILL.md', source: 'own',
            what: 'The OpenAI skill layout reads SKILL.md next to a manifest.' },
};

export const providerNames = () => Object.keys(PROVIDERS);

const clean = (k) => !k.startsWith('$');

/** The canonical journey, rendered. Identical bytes in every pack, by construction. */
export function renderJourney(p) {
  const cmds = Object.entries(p.commands).filter(([k]) => clean(k));
  const exits = Object.entries(p.exitContract).filter(([k]) => clean(k));
  const out = [
    '# The SiteSmith journey',
    '',
    'Generated from `product/pipeline.json`. Do not edit this file: edit the pipeline and',
    'reinstall. Any pack whose journey differs from that file fails `tools/test-pipeline-drift.mjs`.',
    '',
    '## Quickstart',
    '',
    '```bash',
    ...p.quickstart,
    '```',
    '',
    '## Commands',
    '',
    '| command | who does the work |',
    '| --- | --- |',
    ...cmds.map(([n, does]) => `| \`${n}\` | ${does} |`),
    '',
    '## Exit codes',
    '',
    'Every command uses these. A blocker is never reported as success.',
    '',
    '| code | meaning |',
    '| --- | --- |',
    ...exits.map(([c, meaning]) => `| ${c} | ${meaning} |`),
    '',
    '## Steps, in order',
    '',
  ];
  for (const s of p.steps) {
    out.push(`### ${s.id}`, '');
    if (s.command) out.push(`\`${s.command}\``, '');
    out.push(`**Who.** ${s.does}`, '');
    if (s.module) out.push(`**Module.** \`${s.module}\``, '');
    if (s.reads?.length) out.push(`**Reads.** ${s.reads.map((r) => `\`${r}\``).join(', ')}`, '');
    if (s.writes?.length) out.push(`**Writes.** ${s.writes.map((r) => `\`${r}\``).join(', ')}`, '');
    if (s.agentThenDoes) out.push(`**Then the agent.** ${s.agentThenDoes}`, '');
    if (s.stopsWhen) out.push(`**Stops when.** ${s.stopsWhen}`, '');
  }
  out.push('## Before it ships', '',
    ...p.release.requires.map((r) => `- ${r}`), '',
    p.release.neverClaims, '');
  return out.join('\n');
}

/**
 * The provider's own entry file, where the skill does not already supply one.
 * Returns null when the provider reads SKILL.md, which is the skill itself.
 */
export function entryFor(provider, p) {
  const cfg = PROVIDERS[provider];
  if (!cfg) throw new Error(`unknown provider: ${provider}`);
  if (cfg.source === 'own') return null;

  const body = [
    '',
    'Design, build, redesign and audit websites that do not look AI-generated.',
    '',
    'Read `SKILL.md` in this directory first. It is the skill. The journey below is generated',
    'from `product/pipeline.json` and is the same in every provider pack.',
    '',
    renderJourney(p).split('\n').slice(4).join('\n'),
  ].join('\n');

  const head = {
    codex: '# AGENTS.md, SiteSmith\n',
    cursor: [
      '---',
      'description: SiteSmith, build websites that do not look AI-generated',
      'globs: ["**/*.html","**/*.css","**/*.tsx","**/*.jsx","**/*.vue","**/*.astro"]',
      'alwaysApply: false',
      '---',
      '',
    ].join('\n'),
  }[provider];

  return head + body;
}

/**
 * Extra files a provider needs beyond its entry. Shape only: the OpenAI skill validator
 * has not been run against this, and product/pipeline.json says so rather than claiming
 * portability nobody measured.
 */
export function extrasFor(provider, p) {
  if (provider !== 'openai') return {};
  const cmds = Object.keys(p.commands).filter(clean);
  return {
    'openai.yaml': [
      'name: sitesmith',
      `version: "${p.v}"`,
      'entrypoint: SKILL.md',
      'description: >-',
      '  Design, build, redesign and audit websites and web apps that do not look',
      '  AI-generated. Generated from product/pipeline.json.',
      'commands:',
      ...cmds.map((c) => `  - ${c}`),
      `status: ${p.providers.openai.status}`,
      `proof: "${p.providers.openai.proof}"`,
      '',
    ].join('\n'),
  };
}

/** Every generated file for one pack, keyed by its path inside the pack directory. */
export function packFiles(provider, p) {
  const files = { 'JOURNEY.md': renderJourney(p) };
  const entry = entryFor(provider, p);
  if (entry !== null) files[PROVIDERS[provider].entry] = entry;
  Object.assign(files, extrasFor(provider, p));
  return files;
}
